version: "3.7"

networks:
  network:

services:
  redis:
    image: redis:latest
    networks:
      - network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    volumes:
      - ${PWD}:/srv/worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
